Lena naumova
OxyNett/1_147_2020 pull request #24
Opened 2020-11-03 13:28 UTC by LenaNaumova

2020-12-05 15:29 UTC, LenaNaumova commented on KlassNet.cpp
> +﻿// KlassNet.cpp : Этот файл содержит функцию "main". Здесь начинается и заканчивается выполнение программы.
задача для Оксаны Сергеевны

2020-12-05 15:32 UTC, LenaNaumova reviewed
Задача для Оксаны Сергеевны

2020-12-16 07:10 UTC, jskonst requested changes

2020-12-16 07:10 UTC, jskonst commented on 4chisla.cpp
> +	int i;
?

2020-12-16 07:10 UTC, jskonst commented on 4chisla.cpp
> +	int i;
Зачем объявлять без инициализации

2020-12-16 07:10 UTC, jskonst commented on 4chisla.cpp
> +	for (i = 0; i < N; i++)
```c++
for (int i ....
```

2020-12-16 07:10 UTC, jskonst commented on KlassKonst.cpp
> +	//впринцепе, в данной программе диструктор и не нужен.
Тогда удалите код :)

2020-12-16 07:10 UTC, jskonst commented on KlassNet.cpp
> +    string name;
Поля в Private

2020-12-16 07:10 UTC, jskonst commented on KlassNet.cpp
> +    Person(string n)
```c+
Person(string n): Person(n, 18, 3.8) {}
```

2020-12-16 07:10 UTC, jskonst commented on dzkonstantinov2.0/Calc.cpp
> +		std::cout << x << "\t" << y << std::endl;
Уберите вывод в консоль из самой функции

2020-12-16 07:10 UTC, jskonst commented on dzkonstantinov2.0/Calc.cpp
> +	return;
Тут верните посчитанные значения

2020-12-16 07:10 UTC, jskonst commented on dzkonstantinov2.0/dzkonstantinov2.0.cpp
> +	taskA(a, b, xn, xk, dx);
Нет вызова Task B

2020-12-16 07:10 UTC, jskonst commented on dzkonstantinov2.0/Calc.cpp
> +		cout << result << endl;
Верните значение из функции

2020-12-16 07:10 UTC, jskonst commented on klasss.cpp
> +class Location
Недоделанные удаляйте :)

2022-05-28 10:28 UTC, closed without merging